# docker-compose.yml

version: '3.8'

services:
  room_data:
    build:
      context: ./server
      dockerfile: Dockerfile_room_data
    container_name: room_data_server
    ports:
      - "5002:5002"
    volumes:
      - ./server:/app

  room_prediction:
    build:
      context: ./server
      dockerfile: Dockerfile_room_prediction
    container_name: room_prediction_server
    ports:
      - "5003:5003"
    volumes:
      - ./server:/app

  client:
    build: ./client
    container_name: room_search_client
    ports:
      - "8081:80"
    volumes:
      - ./client:/usr/share/nginx/html
