# server/Dockerfile_room_data

FROM python:3.10-slim
WORKDIR /app

# Установка зависимостей
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копирование исходного кода
COPY room_data_collection.py .

# Запуск приложения
CMD ["python", "room_data_collection.py"]
